### ISSUE TITLE
سیستم امتیاز

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/guess_emoji_telegram_bot#2]
یه سیستم امتیاز نیاز داریم که بتونیم گمیفیکیشن داخل بازی پیاده کنیم و همینطور ربات رو سوق بدیم به سمت مسائل مالی.

چیزهایی که توی این فاز نیاز داریم :

- کاربران امتیاز داشته باشن ( یه جور credit )
- تاریخچه رد و بدل امتیاز ها ذخیره شود و بر اساس این تاریخچه امتیاز محاسبه شود ( transaction )
- هرکاربری که اضافه میشه یه مقداری بهش امتیاز اولیه تعلق بگیره
- با حل کردن هر مرحله یه مقداری امتیاز بدست بیاره ( داخل #1  نیاز به بحث سختی هر مرحله رو مطرح کردیم که می تونیم از این قضیه برای دادن امتیاز استفاده کنیم )
- بتونه از این امتیازها برای حل مراحل استفاده کنه ( داخل #1 اضافه کردن راهنمایی به هر مرحله رو اضافه می کنیم که کاربر اگر جایی گیر کنه با راهنمایی گرفتن می تونه سوال رو حل کنه )

### TODO
نحوه دریافت امتیار ها مشخص شود

**Comment by geeksesi** [comment]
# todo 

- [ ]  اضافه کردن راهنمایی
- [ ]  مرتب کردن راهنمایی ها
- [ ]  حذف راهنمایی
- [ ]  راهنمایی های خودکار

**Comment by geeksesi** [comment]
ویرایش - مرتب - حذف راهنمایی رو می ذاریم به عهده phpmyadmin :)
 
دریافت امتیاز به ازای پاسخ دادن به مرحله تکمیل شد.

هزینه راهنمایی کسر میشه. سیستم کردیت اولیه پیاده سازی شده.

لیست راهنمایی ها - اضافه کردن راهنمایی


## [add hint](https://github.com/geeksesi/guess_emoji_telegram_bot/blob/master/app/Controller/Admin/AddHintController.php)
```
!aNewHints LEVEL_ID
TEXT - ORDERS
```
## [list of hints](https://github.com/geeksesi/guess_emoji_telegram_bot/blob/master/app/Controller/Admin/ListHintsController.php)
```
// All of hints
!listHints 

// Hints for a special level_id
!listHints LEVEL_ID
```
